import { createHash } from 'node:crypto';

// Real visitor IP: Cloudflare first, then X-Forwarded-For, then empty.
export function clientIp(headers: Headers): string {
  const cf = headers.get('cf-connecting-ip');
  if (cf) return cf;
  const xff = headers.get('x-forwarded-for');
  if (xff) return xff.split(',')[0].trim();
  return headers.get('x-real-ip') ?? '';
}

// Country from the Cloudflare header (free). Empty if missing.
export function countryFromHeaders(headers: Headers): string {
  const c = headers.get('cf-ipcountry');
  if (!c || c === 'XX' || c === 'T1') return '';
  return c;
}

// Visitor identifier. Preferred: a stable first-party id generated by the
// tracker (localStorage), hashed with the server salt. It enables returning
// visitors, retention cohorts and revenue attribution. Fallback when the
// id is missing (old script, storage blocked): salted daily-rotating hash.
export function visitorId(ip: string, ua: string, iid?: string): string {
  const salt = process.env.AUTH_SECRET ?? '';
  if (iid && /^[a-z0-9-]{8,64}$/i.test(iid)) {
    return createHash('sha256').update(`${salt}|iid|${iid}`).digest('hex').slice(0, 32);
  }
  const day = new Date().toISOString().slice(0, 10);
  return createHash('sha256').update(`${salt}|${ip}|${ua}|${day}`).digest('hex').slice(0, 32);
}

// City/region from Cloudflare "visitor location headers" (managed transform),
// when enabled. Empty otherwise.
export function cityFromHeaders(headers: Headers): { region: string; city: string } {
  return {
    region: headers.get('cf-region') ?? '',
    city: headers.get('cf-ipcity') ?? '',
  };
}
